version: "3.9"
name: musee
services:
  frontend:
    build:
      context: frontend
    image: musee-frontend
    command: ["npm", "run", "demo"]
    restart: always
    ports:
      - 5173:5173
      - 4173:4173
    volumes:
      - .:/src
      - node-modules:/src/frontend/node_modules
    networks:
      - musee

  backend:
    build:
      context: backend
      target: build-image
    image: musee-backend
    env_file: ./backend/.env
    stdin_open: true
    command: bash
    volumes:
      - .:/home/appuser/src
    networks:
      - musee

volumes:
  node-modules:

networks:
  musee:
